apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avm66saeo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avm66saeo-go 
  name: avm66saeo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: avm66saeo-go 
